module.exports = {
	arrowParens: "always",
	bracketSameLine: false,
	bracketSpacing: false,
	endOfLine: "lf",
	plugins: ["prettier-plugin-svelte"],
	printWidth: 100,
	quoteProps: "as-needed",
	semi: true,
	singleQuote: false,
	svelteAllowShorthand: true,
	svelteIndentScriptAndStyle: true,
	svelteStrictMode: false,
	trailingComma: "all",
	useTabs: true,
};
