name: Deployment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    env:
      RELEASE_VERSION: ${{github.event.inputs.release_version}}
      DOCKER_REGISTRY_REPOSITORY_NAME: ${{vars.DOCKER_REGISTRY_REPOSITORY_NAME}}
      DOCKER_REGISTRY_HOST: ${{vars.DOCKER_REGISTRY_HOST}}
      SSH_DEPLOYMENT_HOST: ${{secrets.SSH_DEPLOYMENT_HOST}}
      SSH_DEPLOYMENT_USERNAME: ${{secrets.SSH_DEPLOYMENT_USERNAME}}
      SSH_DEPLOYMENT_PRIVATE_KEY: ${{secrets.SSH_DEPLOYMENT_PRIVATE_KEY}}
      SSH_DEPLOYMENT_DOCKER_SWARM_SERVICE_NAME: ${{secrets.SSH_DEPLOYMENT_DOCKER_SWARM_SERVICE_NAME}}
    steps:
      - name: Deploy to Docker Swarm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.SSH_DEPLOYMENT_HOST}}
          username: ${{env.SSH_DEPLOYMENT_USERNAME}}
          key: ${{env.SSH_DEPLOYMENT_PRIVATE_KEY}}
          script: |
            docker service update --image ${{env.DOCKER_REGISTRY_HOST}}/${{env.DOCKER_REGISTRY_REPOSITORY_NAME}}:${{env.RELEASE_VERSION}} ${{env.SSH_DEPLOYMENT_DOCKER_SWARM_SERVICE_NAME}}
